config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  #_____/users
  resources :users

  #_____/products
  resources :products do
    get :who_bought, on: :member
  end


  #non-administrative functions are nested under :locale so that there are 'en' and 'es' versions of each of those pages
  #we would outsource the translation of the 'es' (spanish) pages
  #administrative functions (users, products) are not nested under locale b/c it's not our intention to translate those
  #:locale is in parens which is a way to say that it is optional, it will default to location....everything here will be xxx/en
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    #root = http://localhost:3000
    root 'store#index', as: 'store_index', via: :all
  end

end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping Cart App</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller.controller_name %>">

    <div id="banner">
      <br/>

      <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>

      <%= image_tag("logo.svg", alt: "Shopping Cart App", :width => "99999999999999999999") %>
      <span class="title"><%= @page_title %></span>
    </div>

    <div id="columns">
      <div id="side">
          <%if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>

        <ul>
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="http://www..../faq"><%= t('.questions') %></a></li>
          <li><a href="http://www..../news"><%= t('.news') %></a></li>
          <li><a href="http://www..../contact"><%= t('.contact') %></a></li>
        </ul>

        <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
          </ul>
          <%= button_to 'Logout', logout_path, method: :delete %>
        <% end %>
      </div>

      <div id="main">
        <br/>
        <%= yield %>
      </div>
    </div>
  </body>
</html>